name: Release
on:
  push:
    tags:
    - v*
jobs:
  test:
    name: Test All 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: ./Projectfile test-all
    - uses: actions/upload-artifact@v1
      with:
        name: results
        path: tmp/artifacts

  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            TODO - replace with changes
          draft: true
